spring.application.name=core-app

server.port=8080

# Database Connection Config
spring.datasource.url=jdbc:postgresql://localhost:5432/spo-db
spring.datasource.username=postgres
spring.datasource.password=root@2003
spring.datasource.driver-class-name=org.postgresql.Driver
imagekit.public.key=public_RE2rPmzzDHzEdKbqMQQfMLkDxNc=
imagekit.private.key=private_LcU9iUhzILhgqdkUoDpYqWGwUG8=
imagekit.endpoint=https://ik.imagekit.io/pwmw53oeo


# JPA / Hibernate Config
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#it converts java data type to postgresSQL data type and postgresSQL data type back to java data type
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

